config/routes.rb
Rails.application.routes.draw do
  resources :airplanes
  get '/flights/:flight_id/seats/indexfirst',to: 'seats#indexfirst', as: 'firstseat'
  get '/flights/:flight_id/seats/indexeconomy',to: 'seats#indexeconomy', as: 'economyseat'
  get '/flights/:flight_id/seats/indexbusiness',to: 'seats#indexbusiness', as: 'businessseat'
  get '/flights/:flight_id/seats/createeco',to: 'seats#createeco'
  post '/flights/:flight_id/seats/createeco',to: 'seats#createeco',as:"createeco"
  get '/users/:user_id/bookings', to: 'bookings#index', as: 'bookings_index'
  post '/users/:user_id/flights/:flight_id/bookings', to: 'bookings#create', as: 'bookings'
  get '/users/:user_id/flights/:flight_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#show', as: 'booking'
  patch '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  put '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  delete '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#destroy'

  get '/search_pnr', to: 'flights#search_pnr', as: 'search_pnr'
  get 'bookings/:booking_id/seatmap', to: 'flights#seatmap', as: 'seatmap'
  post '/bookings/:booking_id/seatmap', to: 'bookings#seatmap'
  post '/seatconfirm', to: 'bookings#seatconfirm' , as: 'seatconfirm'
  root to: 'flights#home'
  devise_for :users
  resources :flights do
  	resources :businesses
  	resources :economies
  	resources :firstclasses
  end

  get '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightnew', as: 'airplane_flight'
  post '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightcreate'
  get '/bookings/:booking_id/upgrade', to: 'bookings#upgrade', as: 'booking_upgrade'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradecreate'
  get '/users/:user_id/flights/finder', to: 'flights#finder', as: 'flights_finder'
  post '/users/:user_id/flights/finder',to: 'flights#finderc'
  get '/flights/:id/seatconfig', to: 'flights#seatcon',as: 'seat'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @flight= Flight.find(params[:flight_id])
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @flight = Flight.find(params[:flight_id])
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @flight = Flight.find(params[:flight_id])
    @business = Business.new(business_params)
  
    respond_to do |format|
      if @business.save

    total = @business.seat * @business.row
    @business.update_attributes(total: total,availability: total)
      @flight.business = @business
     
     @x=1
        loop do
          if ((@x % @business.seat) == 1 && (@x ==(@business.emergency * @business.seat) - @business.seat + 1))
            @seat = @flight.seats.create(seatclass:'business',pnr: 0,seatnumber: @x,seattype: 'window_emergency',price: ((115*@business.price)/100),flight_id: @flight.id,booking_id: nil)
          elsif ((@x % @business.seat) == 0)
            @seat = @flight.seats.create(seatclass:'business',pnr: 0,seatnumber: @x,seattype: 'aisle',:price=> @business.price,flight_id: @flight.id,booking_id: nil)
          elsif ((@x % @business.seat == 1)&& (@x % @business.emergency) > 0)
            @seat = @flight.seats.create(seatclass:'business',pnr: 0,seatnumber: @x,seattype: 'window',price: @business.price,flight_id: @flight.id,booking_id: nil)
          else
            @seat = @flight.seats.create(seatclass:'business',pnr: 0,seatnumber: @x,seattype: 'normal',price: @business.price,flight_id: @flight.id,booking_id: nil)
          end
          @x+=1
          if(@x>@business.total)
            break
          end
        end
    
        
        format.html { redirect_to @flight, notice: 'Business Configuration was updated successfully.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:seat, :row, :price, :emergency)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, url: flight_businesses_path , local: true do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%#= form.hidden_field :flight_id,value: @flight.id %>

   <div class="field">
    <%= form.label :'Seats in a Row' %>
    <%= form.number_field :seat %>
  </div>

  <div class="field">
    <%= form.label :'Total Rows' %>
    <%= form.number_field :row %>
  </div>

  <div class="field">
    <%= form.label :'Base Price' %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :'Row with Emergency exit' %>
    <%= form.number_field :emergency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/_show.html.erb
<p>
  <strong>Seats in a row:</strong>
  <%= @flight.business.seat %>
</p>

<p>
  <strong>Number of Rows:</strong>
  <%= @flight.business.row %>
</p>

<p>
  <strong>Base Price:</strong>
  <%= @flight.business.price %>
</p>

<p>
  <strong>Total Seats:</strong>
  <%= @flight.business.total %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @flight.business.availability %>
</p>

<p>
  <strong>Emergency Window in row:</strong>
  <%= @flight.business.emergency %>
</p>

<%= link_to 'seats', businessseat_path(@flight) %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Seat</th>
      <th>Row</th>
      <th>Price</th>
      <th>Total</th>
      <th>Emergency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.seat %></td>
        <td><%= business.row %></td>
        <td><%= business.price %></td>
        <td><%= business.total %></td>
        <td><%= business.emergency %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_flight_business_path %>

app/views/businesses/new.html.erb
<h1>Create Business Configuration</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', flight_path(params[:flight_id]) %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seat:</strong>
  <%= @business.seat %>
</p>

<p>
  <strong>Row:</strong>
  <%= @business.row %>
</p>

<p>
  <strong>Price:</strong>
  <%= @business.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @business.total %>
</p>

<p>
  <strong>Emergency:</strong>
  <%= @business.emergency %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>