config/routes.rb
Rails.application.routes.draw do
  resources :airplanes
  get '/flights/:flight_id/seats/indexfirst',to: 'seats#indexfirst', as: 'firstseat'
  get '/flights/:flight_id/seats/indexeconomy',to: 'seats#indexeconomy', as: 'economyseat'
  get '/flights/:flight_id/seats/indexbusiness',to: 'seats#indexbusiness', as: 'businessseat'
  get '/flights/:flight_id/seats/createeco',to: 'seats#createeco'
  post '/flights/:flight_id/seats/createeco',to: 'seats#createeco',as:"createeco"
  get '/users/:user_id/bookings', to: 'bookings#index', as: 'bookings_index'
  post '/users/:user_id/flights/:flight_id/bookings', to: 'bookings#create', as: 'bookings'
  get '/users/:user_id/flights/:flight_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#show', as: 'booking'
  patch '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  put '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  delete '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#destroy'

  get '/search_pnr', to: 'flights#search_pnr', as: 'search_pnr'
  get 'bookings/:booking_id/seatmap', to: 'flights#seatmap', as: 'seatmap'
  post '/bookings/:booking_id/seatmap', to: 'bookings#seatmap'
  post '/seatconfirm', to: 'bookings#seatconfirm' , as: 'seatconfirm'
  root to: 'flights#home'
  devise_for :users
  resources :flights do
  	resources :businesses
  	resources :economies
  	resources :firstclasses
  end

  get '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightnew', as: 'airplane_flight'
  post '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightcreate'
  get '/bookings/:booking_id/upgrade', to: 'bookings#upgrade', as: 'booking_upgrade'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradecreate'
  get '/users/:user_id/flights/finder', to: 'flights#finder', as: 'flights_finder'
  post '/users/:user_id/flights/finder',to: 'flights#finderc'
  get '/flights/:id/seatconfig', to: 'flights#seatcon',as: 'seat'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :airplane, optional: true
	has_one :economy
	has_one :firstclass
	has_one :business
	has_many :bookings
	has_many :seats, dependent: :destroy
	before_destroy :destroybooking
	validates :name,  presence: true
	validates :source,  presence: true
	validates :destination, presence: true
	validates :dateofflight, presence: true
	validate :date_cannot_be_in_the_past
    validate :end_must_be_after_start
    validate :source_dest
    before_save :capitalizestring

    def source_dest
    	if(source.downcase === destination.downcase)
    		errors.add(:destination, "cannot be same as source")
    	end
    end

    def capitalizestring
    	self.source = source.capitalize
    	self.destination = destination.capitalize
    end

    def end_must_be_after_start
	  if arrive <= depart
	    errors.add(:arrive, "cannot be before departure")
	  end
    end

	def date_cannot_be_in_the_past
	   if (dateofflight.present? && dateofflight.past?)
	      errors.add(:dateofflight, "can't be in the past")
	    end
	 end 

	def destroybooking
		if(self.bookings.exists?)
		self.bookings.destroy_all
		end
		if(!self.firstclass.nil?)
		self.firstclass.destroy
		end
		if(!self.business.nil?)
		self.business.destroy
		end
		if(!self.economy.nil?)
		self.economy.destroy
	end
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate_user!, except: [:home]
before_action :set_flight, only: [:show, :edit, :update, :destroy]
before_action :admin_check, only: [:show,:destroy,:create,:update,:destroy, :new]
  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  def search_pnr
    @pnr= params[:pnr]
    @booking = Booking.where(:pnr => @pnr).last 
    if (@booking.nil?)
            redirect_to root_path, alert: "Enter a valid pnr number"
            return
          else
              redirect_to seatmap_path(@booking)
          end
  end

  def seatmap
    @booking = Booking.find(params[:booking_id])
    @booking.seatofbookings.destroy_all
    puts @booking
    puts @booking.flight.id
      if (@booking.seatclass==='first')
        @seater = @booking.flight.firstclass.seat
        @seats = Seat.where(:flight_id => @booking.flight.id, :seatclass => 'first').order(:seatnumber)
      elsif (@booking.seatclass==='business')
        @seater = @booking.flight.business.seat
        @seats = Seat.where(:flight_id => @booking.flight.id, :seatclass => 'business').order(:seatnumber)
      else
        @seater = @booking.flight.economy.seat
        @seats = Seat.where(:flight_id => @booking.flight.id, :seatclass => 'economy').order(:seatnumber)
      end
    puts @seats
    puts @seater
  end

  def finder
  end

  def finderc
    @date = params[:dateofflight]
    @source = params[:source].capitalize
    @dest = params[:destination].capitalize

    if((@date === "") && (@source === "") && (@dest === ""))
      @flights = Flight.all
      puts 1
    elsif((@date === "") && (@dest === ""))
      @flights = Flight.where(source: @source)
      puts 5
    elsif((@date === "") && (@source === ""))
      @flights = Flight.where(destination: @dest)
      puts 6
    elsif((@source === "") && (@dest === ""))
      @flights = Flight.where(dateofflight: @date)
      puts 7
    elsif (@date === "")
      @flights = Flight.where(source: @source,destination: @dest)
      puts 1
    elsif(@source === "")
      @flights= Flight.where(dateofflight: @date,destination: @dest)
      puts 2
    elsif(@dest === "")
      @flights= Flight.where(dateofflight: @date,source: @source)
      puts 3
    else
      @flights = Flight.where(dateofflight: @date,source: @source, destination: @dest)
      puts 8
    end
    if (!@flights.exists?)
    redirect_to flights_finder_path, alert: "Sorry no flights available for the given data"
    puts 'hygikujhoik'
    else
      render :book
    end
  end

  def home
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  def seatcon
    @flight = Flight.find(params[:id])
    puts @flight.id
    @firstclass = Firstclass.where(:flight_id => @flight.id)
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :new, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:name, :source, :destination, :depart, :arrive, :dateofflight)
    end

    def find_params
      params.permit(:dateofflight,:source,:destination)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :Date %>
    <%= form.date_field(:dateofflight,:order => [:year, :month, :day]) %>
  </div>

  <div class="field">
    <%= form.label :depart %>
    <%= form.time_select :depart %>
  </div>

  <div class="field">
    <%= form.label :arrive %>
    <%= form.time_select :arrive %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_seatmap.html.erb
<% stylesheet_link_tag "/custom.css" %>

<% @x =0 %>
<h2><%= @booking.flight.name %> - <%= @booking.seatclass %> class </h2>
<div class='classmap'>
  <p> Flight head </p>
  <div>
  <p class="left">W</p>
  <p class="right">A</p>
</div>
<br>
  <div>
<% @seats.each do |seat| %>
  
  <% if (seat.available == true) %>
     <% if (!@booking.seatofbookings.where(:seatnumber => seat.seatnumber).exists?) %>
     <% puts !@booking.seatofbookings.where(:seatnumber => seat.seatnumber).exists? %>
      	<div class="seatavailable">
          <% if (@booking.seatofbookings.size < @booking.seats) %>
          <% if (!Seat.where(:booking_id => @booking.id).exists?) %>
          <%= link_to seat.seatnumber , seatmap_path(:seatnumber => seat.seatnumber),method: "post",class: "seat" %>
          <% else %>
          <%= seat.seatnumber %>
          <% end %>
          <% end %>
        </div>

      <% elsif(@booking.seatofbookings.where(:seatnumber => seat.seatnumber).exists?) %>
      <% puts !@booking.seatofbookings.where(:seatnumber => seat.seatnumber).exists? %>
        <div class="myseat">
            <% if (@booking.seatofbookings.size < @booking.seats) %>
            <% if (!Seat.where(:booking_id => @booking.id).exists?) %>
            <%= link_to seat.seatnumber , seatmap_path(:seatnumber => seat.seatnumber),method: "post", class: "seat" %>
            <% else %>
            <%= seat.seatnumber %>
            <% end %>
            <%end%>
            
        </div>
      <%end %>

  <% elsif seat.available == false %>
    	<div class ="seatunavailable">
        <%= seat.seatnumber %>
    	</div>
  <% end %>

  <% @x+=1 %>
  <% if (@x % @seater ==0) %>
  	<br>
  <% end %>
  <% end %>
</div>
</div>
<br>
  <div class="seatavailable"></div> -Seat Available<br>
  <div class="myseat"></div>- Seats Selected<br>
  <div class ="seatunavailable"></div>- Seats Unavailable
  <br>
  Emergency Exit next to seat- <%= @seats.where(:seattype => "window_emergency").first.seatnumber %>
  <br>
   <% if (@booking.seatofbookings.size == @booking.seats) %>
  <% if (!Seat.where(:booking_id => @booking.id).exists?) %>
 <%= link_to 'Confirm' ,seatconfirm_path(:booking_id => @booking.id) ,method: "post" %> |
 <%= link_to 'reset' ,seatmap_path(:booking_id => @booking.id) %>
 <% end %>
 <% end %>
  <%= link_to 'Back' , root_path %>

app/views/flights/book.html.erb
<%= render 'layouts/alerts' %>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Depart</th>
      <th>Arrive</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %></td>
        <td><%= flight.source %></td>
        <td><%= flight.destination %></td>
        <td><%= dateformat(flight.dateofflight) %></td>
        <td><%= timeformat(flight.depart) %></td>
        <td><%= timeformat(flight.arrive) %></td>
        <td><%= link_to 'Book Flight', new_booking_path(current_user,flight) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_path %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/finder.html.erb
<%= form_tag(flights_finder_path, method: "post") do %> 
    
    <div class="field">
      <%= label_tag  :"date of flight" %>
      <%= date_field_tag(:dateofflight, :order => [:year, :month, :day])  %>
    </div>

    <div class="field">
      <%= label_tag :source %>
      <%= text_field_tag :source %>
    </div>

    <div class="field">
      <%= label_tag :destination %>
      <%= text_field_tag :destination %>
    </div>

    <div class="actions">
    <%= submit_tag("Submit") %>
    </div>
    
<% end %>

app/views/flights/flightnew.html.erb
<h1>New Flight</h1>

<%= render 'flightcreate', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/home.html.erb
<h1>WELCOME TO THE FLIGHT APP</h1>

	<% if current_user %>

		<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> |	
		<% if (current_user.admin?) %>	
		<%= link_to 'Flights', flights_path %> |
		<%= link_to 'Airplanes', airplanes_path %> |
		<% end %>
		<%= link_to 'New Booking', flights_finder_path(current_user) %> |
		<% if (current_user.admin?) %>
		<%= link_to 'All Bookings', bookings_index_path(current_user) %>
		<% else %>
		<%= link_to 'My Bookings', bookings_index_path(current_user) %>
		<% end %>
		<%= form_tag(search_pnr_path, method: "get") do %>
		<h2> SELECT SEAT </h2>	
		  <div class="field">
		    <%= label_tag :'PNR Number' %>
		    <%= text_field_tag :pnr %>
		  </div>
		  <div class="actions">
		    <%= submit_tag("Submit") %>
		  </div>
		<% end %>

	<% else %>

		<%= link_to 'Sign Up', new_user_registration_path %> |
		<%= link_to 'Sign In', new_user_session_path %>

	<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Depart</th>
      <th>Arrive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %></td>
        <td><%= flight.source %></td>
        <td><%= flight.destination %></td>
        <td><%= dateformat(flight.dateofflight) %></td>
        <td><%= timeformat(flight.depart) %></td>
        <td><%= timeformat(flight.arrive) %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', airplanes_path %> |
<%= link_to 'Back', root_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/seatcon.html.erb
<h2> Seat Configurations For <%= @flight.name %> </h2>

<table>
	<thead>
	 	<tr>
			<th><h2>First Class Configuration</h2></th>
			<th></th>
			<th></th>
			<th><h2>Business Class Configuration</h2></th>
			<th></th>
			<th></th>
			<th><h2>Economy Class Configuration</h2></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<% if (@flight.firstclass.nil?) %>
				<% else %>
					<%= render 'firstclasses/show' %>
				<% end %>
			</td>
			<td></td>
			<td></td>
			<td>
				<% if (@flight.business.nil?) %>
				<% else %>
					<%= render 'businesses/show' %>
				<% end %>
			</td>
			<td></td>
			<td></td>
			<td>
				<% if (@flight.economy.nil?) %>
				<% else %>
					<%= render 'economies/show' %>
				<% end %>
			</td>
		</tr>
	</tbody>

</table>
<%= link_to 'Back', flight_path(params[:id]) %>

app/views/flights/seatmap.html.erb
<%= render partial: 'seatmap' %>

app/views/flights/show.html.erb
<h2>FLIGHT DETAILS</h2>
<p>
  <strong>Name:</strong>
  <%= @flight.name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @flight.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= dateformat(@flight.dateofflight) %>
</p>

<p>
  <strong>Depart:</strong>
  <%= timeformat(@flight.depart) %>
</p>

<p>
  <strong>Arrive:</strong>
  <%= timeformat(@flight.arrive) %>
</p>
<% if @flight.firstclass.nil? %>
<%= link_to 'First Class Configuration',new_flight_firstclass_path(@flight) %> 
<% end %>
<br>
<% if @flight.business.nil? %>
<%= link_to 'Business Class Configuration',new_flight_business_path(@flight) %>
<% end %>
<br>
<% if @flight.economy.nil? %>
<%= link_to 'Economy Class Configuration',new_flight_economy_path(@flight) %>
<% end %>
<br><br>

<%= link_to 'Seat Configuration', seat_path(@flight) %> |
<%= link_to 'Back', flights_path %>