config/routes.rb
Rails.application.routes.draw do
  resources :airplanes
  get '/flights/:flight_id/seats/indexfirst',to: 'seats#indexfirst', as: 'firstseat'
  get '/flights/:flight_id/seats/indexeconomy',to: 'seats#indexeconomy', as: 'economyseat'
  get '/flights/:flight_id/seats/indexbusiness',to: 'seats#indexbusiness', as: 'businessseat'
  get '/flights/:flight_id/seats/createeco',to: 'seats#createeco'
  post '/flights/:flight_id/seats/createeco',to: 'seats#createeco',as:"createeco"
  get '/users/:user_id/bookings', to: 'bookings#index', as: 'bookings_index'
  post '/users/:user_id/flights/:flight_id/bookings', to: 'bookings#create', as: 'bookings'
  get '/users/:user_id/flights/:flight_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#show', as: 'booking'
  patch '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  put '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  delete '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#destroy'

  get '/search_pnr', to: 'flights#search_pnr', as: 'search_pnr'
  get 'bookings/:booking_id/seatmap', to: 'flights#seatmap', as: 'seatmap'
  post '/bookings/:booking_id/seatmap', to: 'bookings#seatmap'
  post '/seatconfirm', to: 'bookings#seatconfirm' , as: 'seatconfirm'
  root to: 'flights#home'
  devise_for :users
  resources :flights do
  	resources :businesses
  	resources :economies
  	resources :firstclasses
  end

  get '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightnew', as: 'airplane_flight'
  post '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightcreate'
  get '/bookings/:booking_id/upgrade', to: 'bookings#upgrade', as: 'booking_upgrade'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradecreate'
  get '/users/:user_id/flights/finder', to: 'flights#finder', as: 'flights_finder'
  post '/users/:user_id/flights/finder',to: 'flights#finderc'
  get '/flights/:id/seatconfig', to: 'flights#seatcon',as: 'seat'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/firstclasses_controller.rb
class FirstclassesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_firstclass, only: [:show, :edit, :update, :destroy]

  # GET /firstclasses
  # GET /firstclasses.json
  def index
    @flight= Flight.find(params[:flight_id])
    @firstclasses = Firstclass.all
  end

  # GET /firstclasses/1
  # GET /firstclasses/1.json
  def show
  end

  # GET /firstclasses/new
  def new
        @flight = Flight.find(params[:flight_id])
    @firstclass = Firstclass.new
  end

  # GET /firstclasses/1/edit
  def edit
  end

  # POST /firstclasses
  # POST /firstclasses.json
  def create
     @flight = Flight.find(params[:flight_id])
     @firstclass = Firstclass.new(firstclass_params)

     respond_to do |format|
      if @firstclass.save
     total = @firstclass.seat * @firstclass.row
    @firstclass.update_attributes(total: total,availability: total)
         @flight.firstclass = @firstclass
     
      @x=1
        loop do
          if ((@x % @firstclass.seat == 1) && (@x == ((@firstclass.emergency * @firstclass.seat)- @firstclass.seat + 1)))
            @seat = @flight.seats.create(seatclass:'first',pnr: 0,seatnumber: @x,seattype: 'window_emergency',price: ((115*@firstclass.price)/100),flight_id: @flight.id,booking_id: nil)
          elsif (@x % @firstclass.seat == 0)
            @seat = @flight.seats.create(seatclass:'first',pnr: 0,seatnumber: @x,seattype: 'aisle',:price=> @firstclass.price,flight_id: @flight.id,booking_id: nil)
          elsif (@x % @firstclass.seat == 1 && @x % @firstclass.emergency > 0)
            @seat = @flight.seats.create(seatclass:'first',pnr: 0,seatnumber: @x,seattype: 'window',price: @firstclass.price,flight_id: @flight.id,booking_id: nil)
          else
            @seat = @flight.seats.create(seatclass:'first',pnr: 0,seatnumber: @x,seattype: 'normal',price: @firstclass.price,flight_id: @flight.id,booking_id: nil)
          end
          @x+=1
          if(@x>@firstclass.total)
            break
          end
        end

    
       
        format.html { redirect_to @flight, notice: 'Firstclass Configuration was updated successfully.' }
        format.json { render :show, status: :created, location: @firstclass }
      else
        format.html { render :new }
        format.json { render json: @firstclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firstclasses/1
  # PATCH/PUT /firstclasses/1.json
  def update
    respond_to do |format|
      if @firstclass.update(firstclass_params)
        format.html { redirect_to @firstclass, notice: 'Firstclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @firstclass }
      else
        format.html { render :edit }
        format.json { render json: @firstclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firstclasses/1
  # DELETE /firstclasses/1.json
  def destroy
    @firstclass.destroy
    respond_to do |format|
      format.html { redirect_to firstclasses_url, notice: 'Firstclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firstclass
      @firstclass = Firstclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firstclass_params
      params.require(:firstclass).permit(:seat, :row, :price, :emergency)
    end
end

app/helpers/firstclasses_helper.rb
module FirstclassesHelper
end

app/views/firstclasses/_form.html.erb
<%= form_for @firstclass, url: flight_firstclasses_path , local: true do |form| %>
  <% if firstclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firstclass.errors.count, "error") %> prohibited this firstclass from being saved:</h2>

      <ul>
      <% firstclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%#= form.hidden_field :flight_id,value: @flight.id %>

  <div class="field">
    <%= form.label :'Seats in a Row' %>
    <%= form.number_field :seat %>
  </div>

  <div class="field">
    <%= form.label :'Total Rows' %>
    <%= form.number_field :row %>
  </div>

  <div class="field">
    <%= form.label :'Base Price' %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :'Row with Emergency exit' %>
    <%= form.number_field :emergency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/firstclasses/_show.html.erb
<p>
  <strong>Seats in a row:</strong>
  <%= @flight.firstclass.seat %>
</p>

<p>
  <strong>Number of Rows:</strong>
  <%= @flight.firstclass.row %>
</p>

<p>
  <strong>Base Price:</strong>
  <%= @flight.firstclass.price %>
</p>

<p>
  <strong>Total Seats:</strong>
  <%= @flight.firstclass.total %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @flight.firstclass.availability %>
</p>

<p>
  <strong>Emergency Window in row:</strong>
  <%= @flight.firstclass.emergency %>
</p>

<%= link_to 'seats', firstseat_path(@flight) %>

app/views/firstclasses/edit.html.erb
<h1>Editing Firstclass</h1>

<%= render 'form', firstclass: @firstclass %>

<%= link_to 'Show', @firstclass %> |
<%= link_to 'Back', firstclasses_path %>

app/views/firstclasses/index.html.erb
<h1>Firstclasses</h1>

<table>
  <thead>
    <tr>
      <th>Seat</th>
      <th>Row</th>
      <th>Price</th>
      <th>Total</th>
      <th>Emergency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firstclasses.each do |firstclass| %>
      <tr>
        <td><%= firstclass.seat %></td>
        <td><%= firstclass.row %></td>
        <td><%= firstclass.price %></td>
        <td><%= firstclass.total %></td>
        <td><%= firstclass.emergency %></td>
        <td><%= link_to 'Show', firstclass %></td>
        <td><%= link_to 'Edit', edit_firstclass_path(firstclass) %></td>
        <td><%= link_to 'Destroy', firstclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firstclass', new_flight_firstclass_path %>

app/views/firstclasses/new.html.erb
<h1>Create Firstclass Configuration</h1>

<%= render 'form', firstclass: @firstclass %>

<%= link_to 'Back', flight_path(params[:flight_id]) %>

app/views/firstclasses/show.html.erb
<p>
  <strong>Seat in a Row:</strong>
  <%= @firstclass.seat %>
</p>

<p>
  <strong>Number of Rows:</strong>
  <%= @firstclass.row %>
</p>

<p>
  <strong>Price:</strong>
  <%= @firstclass.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @firstclass.total %>
</p>

<p>
  <strong>Emergency in Row:</strong>
  <%= @firstclass.emergency %>
</p>

<%= link_to 'Edit', edit_firstclass_path(@firstclass) %> |
<%= link_to 'Back', firstclasses_path %>