config/routes.rb
Rails.application.routes.draw do
  resources :airplanes
  get '/flights/:flight_id/seats/indexfirst',to: 'seats#indexfirst', as: 'firstseat'
  get '/flights/:flight_id/seats/indexeconomy',to: 'seats#indexeconomy', as: 'economyseat'
  get '/flights/:flight_id/seats/indexbusiness',to: 'seats#indexbusiness', as: 'businessseat'
  get '/flights/:flight_id/seats/createeco',to: 'seats#createeco'
  post '/flights/:flight_id/seats/createeco',to: 'seats#createeco',as:"createeco"
  get '/users/:user_id/bookings', to: 'bookings#index', as: 'bookings_index'
  post '/users/:user_id/flights/:flight_id/bookings', to: 'bookings#create', as: 'bookings'
  get '/users/:user_id/flights/:flight_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
  get '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#show', as: 'booking'
  patch '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  put '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#update'
  delete '/users/:user_id/flights/:flight_id/bookings/:id', to: 'bookings#destroy'

  get '/search_pnr', to: 'flights#search_pnr', as: 'search_pnr'
  get 'bookings/:booking_id/seatmap', to: 'flights#seatmap', as: 'seatmap'
  post '/bookings/:booking_id/seatmap', to: 'bookings#seatmap'
  post '/seatconfirm', to: 'bookings#seatconfirm' , as: 'seatconfirm'
  root to: 'flights#home'
  devise_for :users
  resources :flights do
  	resources :businesses
  	resources :economies
  	resources :firstclasses
  end

  get '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightnew', as: 'airplane_flight'
  post '/airplanes/:airplane_id/flights/new', to: 'airplanes#flightcreate'
  get '/bookings/:booking_id/upgrade', to: 'bookings#upgrade', as: 'booking_upgrade'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradecreate'
  get '/users/:user_id/flights/finder', to: 'flights#finder', as: 'flights_finder'
  post '/users/:user_id/flights/finder',to: 'flights#finderc'
  get '/flights/:id/seatconfig', to: 'flights#seatcon',as: 'seat'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/economy.rb
class Economy < ApplicationRecord
	belongs_to :flight, optional: true
	validates :seat, presence: true
	validates :row, presence: true
	validates :price, presence: true
	validates :emergency, presence: true
	validate :checkemer

	def checkemer
		if(emergency.to_i>row.to_i)
			errors.add(:emergency, "cannot be more than row")
		end
	end
end

app/controllers/economies_controller.rb
class EconomiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_economy, only: [:show, :edit, :update, :destroy]

  # GET /economies
  # GET /economies.json
  def index
    @flight= Flight.find(params[:flight_id])
    @economies = Economy.all
  end

  # GET /economies/1
  # GET /economies/1.json
  def show
  end

  # GET /economies/new
  def new
        @flight = Flight.find(params[:flight_id])
    @economy = Economy.new
  end

  # GET /economies/1/edit
  def edit
  end

  # POST /economies
  # POST /economies.json
  def create
    @flight = Flight.find(params[:flight_id])
    @economy = Economy.new(economy_params)

        respond_to do |format|
      if @economy.save
      
    total = @economy.seat * @economy.row
    @economy.update_attributes(total: total,availability: total)
    @flight.economy = @economy

    @x=1
        loop do
          if ((@x % @economy.seat) == 1 && (@x ==(@economy.emergency*(@economy.seat))- @economy.seat + 1))
            @seat = @flight.seats.create(seatclass:'economy',pnr: 0,seatnumber: @x,seattype: 'window_emergency',price: ((115*@economy.price)/100),flight_id: @flight.id,booking_id: nil)
          elsif ((@x % @economy.seat) == 0)
            @seat = @flight.seats.create(seatclass:'economy',pnr: 0,seatnumber: @x,seattype: 'aisle',:price=> @economy.price,flight_id: @flight.id,booking_id: nil)
          elsif ((@x % @economy.seat == 1)&& (@x % @economy.emergency) > 0)
            @seat = @flight.seats.create(seatclass:'economy',pnr: 0,seatnumber: @x,seattype: 'window',price: @economy.price,flight_id: @flight.id,booking_id: nil)
          else
            @seat = @flight.seats.create(seatclass:'economy',pnr: 0,seatnumber: @x,seattype: 'normal',price: @economy.price,flight_id: @flight.id,booking_id: nil)
          end
          @x+=1
          if(@x>@economy.total)
            break
          end
        end


        format.html { redirect_to @flight, notice: 'Economy Configuration was updated successfully.' }
        format.json { render :show, status: :created, location: @economy }
      else
        format.html { render :new }
        format.json { render json: @economy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /economies/1
  # PATCH/PUT /economies/1.json
  def update
    respond_to do |format|
      if @economy.update(economy_params)
        format.html { redirect_to @economy, notice: 'Economy was successfully updated.' }
        format.json { render :show, status: :ok, location: @economy }
      else
        format.html { render :edit }
        format.json { render json: @economy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /economies/1
  # DELETE /economies/1.json
  def destroy
    @economy.destroy
    respond_to do |format|
      format.html { redirect_to economies_url, notice: 'Economy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_economy
      @economy = Economy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def economy_params
      params.require(:economy).permit(:seat, :row, :price, :emergency)
    end
end

app/helpers/economies_helper.rb
module EconomiesHelper
end

app/views/economies/_form.html.erb
<%= form_for @economy, url: flight_economies_path , local: true do |form| %>
  <% if economy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(economy.errors.count, "error") %> prohibited this economy from being saved:</h2>

      <ul>
      <% economy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%#= form.hidden_field :flight_id,value: @flight.id %>

   <div class="field">
    <%= form.label :'Seats in a Row' %>
    <%= form.number_field :seat %>
  </div>

  <div class="field">
    <%= form.label :'Total Rows' %>
    <%= form.number_field :row %>
  </div>

  <div class="field">
    <%= form.label :'Base Price' %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :'Row with Emergency exit' %>
    <%= form.number_field :emergency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/economies/_show.html.erb
<p>
  <strong>Seats in a row:</strong>
  <%= @flight.economy.seat %>
</p>

<p>
  <strong>Number of Rows:</strong>
  <%= @flight.economy.row %>
</p>

<p>
  <strong>Base Price:</strong>
  <%= @flight.economy.price %>
</p>

<p>
  <strong>Total Seats:</strong>
  <%= @flight.economy.total %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @flight.economy.availability %>
</p>

<p>
  <strong>Emergency Window in row:</strong>
  <%= @flight.economy.emergency %>
</p>

<%= link_to 'seats', economyseat_path(@flight) %>

app/views/economies/edit.html.erb
<h1>Editing Economy</h1>

<%= render 'form', economy: @economy %>

<%= link_to 'Show', @economy %> |
<%= link_to 'Back', economies_path %>

app/views/economies/index.html.erb
<h1>Economies</h1>

<table>
  <thead>
    <tr>
      <th>Seat</th>
      <th>Row</th>
      <th>Price</th>
      <th>Total</th>
      <th>Emergency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @economies.each do |economy| %>
      <tr>
        <td><%= economy.seat %></td>
        <td><%= economy.row %></td>
        <td><%= economy.price %></td>
        <td><%= economy.total %></td>
        <td><%= economy.emergency %></td>
        <td><%= link_to 'Show', economy %></td>
        <td><%= link_to 'Edit', edit_economy_path(economy) %></td>
        <td><%= link_to 'Destroy', economy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Economy', new_flight_economy_path %>

app/views/economies/new.html.erb
<h1>Create Economy Configuration</h1>

<%= render 'form', economy: @economy %>

<%= link_to 'Back', flight_path(params[:flight_id]) %>

app/views/economies/show.html.erb
<p>
  <strong>Seat:</strong>
  <%= @economy.seat %>
</p>

<p>
  <strong>Row:</strong>
  <%= @economy.row %>
</p>

<p>
  <strong>Price:</strong>
  <%= @economy.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @economy.total %>
</p>

<p>
  <strong>Emergency:</strong>
  <%= @economy.emergency %>
</p>

<%= link_to 'Edit', edit_economy_path(@economy) %> |
<%= link_to 'Back', economies_path %>